version: 2.1

orbs:
  macos: circleci/macos@2.4.1
  python: circleci/python@2.1.1

jobs:
  tests_macos:
    description: "Run commandson macOS with given Xcode"
    macos:
      xcode: << parameters.xcode_version >>
    parameters:
      xcode_version:
        type: string
    environment:
      LC_ALL: "en_US.UTF-8"
      LANG: "en_US.UTF-8"
    shell: "/bin/bash --login -eo pipefail"
    steps:
      - checkout
      - macos/switch-ruby:
          version: "system"
      - run:
          name: debug | ruby version
          command: |
            .circleci/scripts/cienv | tee -a ~/cienv.txt
      - run:
          name: debug | test pty
          command: |
            brew install stress
            ruby test_pty.rb "echo foo"
            STRESS=y ruby test_pty.rb "echo foo"
      - store_artifacts:
          path: ~/cienv.txt
          destination: cienv.txt
  gather_artifacts:
    description: "Gather artifacts from the jobs"
    executor: python/default
    steps:
      - checkout
      - run:
          name: gather artifacts
          command: |
            .circleci/scripts/circle_artifacts.py
      - store_artifacts:
          path: artifacts.zip
          destination: artifacts.zip

workflows:
  version: 2
  build:
    jobs:
      - tests_macos:
          name: "tests on macOS (Xcode << matrix.xcode_version >>)"
          matrix:
            parameters:
              xcode_version:
                [
                  "12.5.1",
                  "13.4.1",
                  "14.0.1",
                  "14.1.0",
                  "14.2.0",
                  "14.3.1",
                  "15.0.0",
                  "15.0.1",
                  "15.1.0",
                  "15.2.0",
                ]
      - gather_artifacts:
          name: "Gather the data"
          requires:
            - tests_macos
