version: 2.1

orbs:
  macos: circleci/macos@2.4.0

jobs:
  tests_macos:
    description: 'Run commandson macOS with given Xcode'
    macos:
      xcode: << parameters.xcode_version >>
    parameters:
      xcode_version:
        type: string
    environment:
      LC_ALL: 'en_US.UTF-8'
      LANG: 'en_US.UTF-8'
    shell: '/bin/bash --login -eo pipefail'
    steps:
      - checkout
      - macos/switch-ruby:
          version: "system"
      - run:
          name: debug | ruby version
          command: |
            which ruby | tee ~/ruby_version.txt
            ruby -v | tee -a ~/ruby_version.txt
      - store_artifacts:
          path: ~/ruby_version.txt
          destination: ruby_version.txt

workflows:
  version: 2
  build:
    jobs:
      - tests_macos:
          name: 'tests on macOS (Xcode 12.5.1)'
          xcode_version: '12.5.1'
      - tests_macos:
          name: 'tests on macOS (Xcode 13.4.1)'
          xcode_version: '13.4.1'
      - tests_macos:
          name: 'tests on macOS (Xcode 14.3.1)'
          xcode_version: '14.0.1'
      - tests_macos:
          name: 'tests on macOS (Xcode 14.3.1)'
          xcode_version: '14.1.0'
      - tests_macos:
          name: 'tests on macOS (Xcode 14.3.1)'
          xcode_version: '14.2.0'
      - tests_macos:
          name: 'tests on macOS (Xcode 14.3.1)'
          xcode_version: '14.3.1'
      - tests_macos:
          name: 'tests on macOS (Xcode 14.3.1)'
          xcode_version: '15.0.0'
      - tests_macos:
          name: 'tests on macOS (Xcode 15.0.1)'
          xcode_version: '15.0.1'